name: Build and deployment workflow

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    container:
      options: --user 1000
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay
        run: echo "${{ secrets.QUAY_ROBOT_TOKEN }}" | docker login -u "${{ secrets.QUAY_ROBOT_USERNAME }}" --password-stdin quay.io
      - name: Set Git credentials
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Increase version
        run: |
          npm version patch -m "Increment version to %s"
          git push
      - run: |
          make
          make tests-ci
          make build push
